### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [Liquicit/LilithProgressHUD#1]
<img width="355" alt="screen shot 2016-08-15 at 7 07 10 pm" src="https://cloud.githubusercontent.com/assets/6511079/17685713/8080f70a-631b-11e6-9afe-58bc81034e6a.png">

**Comment by Liquicit** [comment]
Thanks for pointing that out. I updated the description.

**Comment by lfarah** [comment]
You're welcome! 😉
